services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes: 
      - vaultwarden_data:/data/
    ports:
      - 82:80

volumes:
  vaultwarden_data:

networks:
  homelab_net:
    external: true
